services:
  httpbin:
    image: mccutchen/go-httpbin:v2.9.0
    environment:
      - MAX_BODY_SIZE=15728640 # 15 MiB
    command: [ "/bin/go-httpbin", "-port", "8000" ]
    ports:
      - 8000:8000
  chown:
    image: alpine:3.16
    command:
      - /bin/sh
      - -c
      - chown -R 101:101 /home/envoy/logs
    volumes:
      - logs:/home/envoy/logs:rw
  envoy:
    depends_on:
      - chown
      - httpbin
    image: ubuntu:22.04
    entrypoint: /envoybin/envoy
    command:
      - -c
      - /conf/envoy-config.yaml
      - --log-level
      - info
      - --component-log-level
      - wasm:debug
      - --log-format [%Y-%m-%d %T.%f][%t][%l][%n] [%g:%#] %v
      - --log-path
      - /home/envoy/logs/envoy.log
      - --file-flush-interval-msec
      - "50"
    volumes:
      - ../envoybin:/envoybin
      - ../../build:/build
      - .:/conf
      - logs:/home/envoy/logs:rw
    ports:
      - 8080:8080

  envoy-logs:
    depends_on:
      - envoy
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - tail -c +0 -f /home/envoy/logs/envoy.log
    volumes:
      - logs:/home/envoy/logs:ro

volumes:
  logs:
