services:
  httpbin:
    image: mccutchen/go-httpbin:v2.9.0
    command: [ "/bin/go-httpbin", "-port", "8080" ]
    ports:
      - "8080:8080"
  chown:
    image: alpine:3.16
    command:
      - /bin/sh
      - -c
      # Early creates the log file so wasm-logs does not fail even if envoy is not yet healthy
      - touch /home/envoy/logs/envoy.log && chown -R 101:101 /home/envoy/logs
    volumes:
      - logs:/home/envoy/logs:rw
  envoy:
    depends_on:
      - chown
      - httpbin
    image: ubuntu:22.04
    entrypoint: /envoybin/envoy
    command:
      - -c
      - ${ENVOY_CONFIG:-/conf/envoy-config.yaml}
      - --log-level
      - error
      - --component-log-level
      - wasm:error
      - --log-format [%Y-%m-%d %T.%f][%t][%l][%n] [%g:%#] %v
      - --log-path
      - /home/envoy/logs/envoy.log
      - --file-flush-interval-msec # Need to force it otherwise FTW is too fast and does not find the logs
      - "10"
    volumes:
      - ../envoybin:/envoybin
      - ../../build:/build
      - .:/conf
      - logs:/home/envoy/logs:rw
    ports:
      - 8081:80
  wasm-logs:
    depends_on:
      - envoy
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - tail -c +0 -f /home/envoy/logs/envoy.log | grep --line-buffered "[error][wasm]" > /home/envoy/logs/ftw.log
    volumes:
      - logs:/home/envoy/logs:rw
  envoy-logs:
    depends_on:
      - envoy
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - tail -c +0 -f /home/envoy/logs/envoy.log > /build/ftw-envoy.log
    volumes:
      - logs:/home/envoy/logs:ro
      - ../../build:/build
  ftw:
    depends_on:
      - envoy-logs
      - wasm-logs
    build:
      context: .
      dockerfile: Dockerfile.ftw
    environment:
      - FTW_CLOUDMODE
      - FTW_INCLUDE
    volumes:
      - logs:/home/envoy/logs:ro
      - ../../build:/build
  ftw-memstats:
    depends_on:
      - ftw
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - "tail -c +0 -f /home/envoy/logs/envoy.log | grep 'Sys: '"
    volumes:
      - logs:/home/envoy/logs:ro
volumes:
  logs:
